name: Test on Linux

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        rust-toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust ${{ matrix.rust-toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install g++-4.8
      run: sudo apt-get install -y g++-4.8
    - name: set DISPLAY env
      run: echo "::set-env DISPLAY=:99.0"
    - name: run cargo test
      uses: GabrielBB/xvfb-action@v1.2
      with:
        run: cargo test --release -- --nocapture
