name: Test on Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    # Disable this on our own internal PRs since it'll be run on the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        rust-toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust ${{ matrix.rust-toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install g++-4.8
      run: sudo apt-get install -y g++-4.8
    - name: set DISPLAY env
      run: echo "::set-env DISPLAY=:99.0"
    - name: run cargo test
      uses: GabrielBB/xvfb-action@e9adbdcd44108e54f12d6a49a373a074385b8512
      with:
        run: cargo test --release -- --nocapture
