name: Test on MacOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    # Disable this on our own internal PRs since it'll be run on the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        rust-toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust ${{ matrix.rust-toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        target: x86_64-apple-darwin
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: update node-gyp to latest
    #   # https://github.com/nodejs/node-gyp/issues/1933#issuecomment-586915535
    #   run: npm install -g node-gyp@latest
    - name: run cargo test
      run: cargo test --release
