name: Test on Windows

on:
  push:
    # Disable this on our own internal PRs.
    branches:
      - master
    pull_request: true

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        rust-toolchain: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Use Rust ${{ matrix.rust-toolchain }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        target: x86_64-pc-windows-msvc
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - name: update node-gyp to latest
    #   # https://github.com/nodejs/node-gyp/issues/1933#issuecomment-586915535
    #   run: npm install -g node-gyp@latest
    - run: npm config set msvs_version 2019
    - name: run cargo test
      run: cargo test --release
